In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a=[1,2,3.5,4]
a

[1, 2, 3.5, 4]

In [5]:
np.array(a)

array([1. , 2. , 3.5, 4. ])

list does not support multi dimension things

In [6]:
l=[[1,2,3],[3,5,6],[7,8,9]]
l

[[1, 2, 3], [3, 5, 6], [7, 8, 9]]

In [7]:
np.array(l)#this is now two dimenssion

array([[1, 2, 3],
       [3, 5, 6],
       [7, 8, 9]])

some array generation function

In [8]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
arr=np.ones((6,6))
arr# doublebracket vector and sible matrix

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
arr=np.linspace(1,4,10)
arr

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

RANDOM GENERATION FUNCTION

In [12]:
np.random.rand(10)# jab 3 aur -3 ke beech me value aati hai use tab standedisation kahte hai aur jab (0 to 1)_>normaalization

array([0.78494628, 0.54574555, 0.55394379, 0.14058997, 0.11438218,
       0.50358535, 0.73278196, 0.35615496, 0.75995384, 0.52335491])

In [13]:
np.random.randn(10)# fo standedisatiom

array([ 0.46991791, -0.93144278,  1.12588906,  0.15125457, -0.90052904,
       -0.32849889,  0.49595401,  0.33720778, -1.40890332,  0.64431925])

In [14]:
np.random.randint(10)# generate a random number from 0 to 10 any ...

1

In [15]:
np.random.randint(10,20,10)

array([11, 17, 15, 14, 11, 12, 11, 15, 16, 16], dtype=int32)

*Array attributes*

In [16]:
l=[[1,2,3],[3,5,6],[7,8,9]]
arr=np.array(l)
arr


array([[1, 2, 3],
       [3, 5, 6],
       [7, 8, 9]])

In [17]:
arr.shape

(3, 3)

In [18]:
arr.size

9

In [19]:
arr.dtype

dtype('int64')

*ARRAY METHOD*

In [20]:
arr.min()

np.int64(1)

In [21]:
arr.max()

np.int64(9)

In [22]:
arr.sum()# sum is in-built in oython

np.int64(44)

In [23]:
np.sum(arr,axis=0)#for row wise summetion it will  be 1 axis

array([11, 15, 18])

In [24]:
np.sum(arr,1)

array([ 6, 14, 24])

In [25]:
arr.mean()

np.float64(4.888888888888889)

In [26]:
arr.std()

np.float64(2.6434171674156266)

In [27]:
arr.argmax()

np.int64(8)

In [28]:
arr.argmin()

np.int64(0)

RESHAOING AND RISIZING

In [29]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [30]:
arr=arr.reshape(6,5)